# yaml-language-server: $schema=https://json.schemastore.org/nuejs-site.json

globals: ["@global"]
libs: ["@library"]

view_transitions: true
native_css_nesting: true
inline_css: true
sections: true

title_template: "priority kids. / %s"
og_image: /img/pk-logo.png
author: priority kids.
favicon: /img/favjjicon.jpg
description: The youth, inspired and ready, for the global community. It’s a priority.
port: 8083

# OG image
origin: https://prioritykids.org
og: /img/pk-logo.png

navigation:
  header:
    - since 1435.: /
    - Contact: /contact/

  footer:
    - ©priority kids. 1447: /

    - we love the youth.
